[supervisord]
nodaemon=true
# Не указываем logfile, чтобы supervisord сам писал в stdout/stderr
# logfile=/tmp/supervisord.log ; Убрано
# logfile_maxbytes=50MB
# logfile_backups=10
loglevel=info
# pidfile=/tmp/supervisord.pid ; supervisord в контейнере может не требовать PID файла
umask=022

[program:php-fpm]
command=/usr/sbin/php-fpm --nodaemonize --fpm-config /usr/local/etc/php-fpm.d/www.conf
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true
# user=www-data ; supervisord запущен от www-data, и php-fpm будет запущен от него же